<?php declare(strict_types = 1);

namespace Everon\Logger\Configurator\Plugin;

use InvalidArgumentException;
use UnexpectedValueException;
use function array_key_exists;
use function ctype_upper;
use function is_array;
use function is_object;
use function method_exists;
use function sprintf;
use function strtolower;
use function trim;

/**
 * Code generated by POPO generator, do not edit.
 * https://packagist.org/packages/popo/generator
 */
class GelfTcpLoggerPluginConfigurator
{
    protected array $data = [
        'logLevel' => 'debug',
        'shouldBubble' => true,
        'host' => \Gelf\Transport\TcpTransport::DEFAULT_HOST,
        'port' => \Gelf\Transport\TcpTransport::DEFAULT_PORT,
        'sslOptions' => null,
        'useSsl' => false,
    ];

    protected array $default = [
        'logLevel' => 'debug',
        'shouldBubble' => true,
        'host' => \Gelf\Transport\TcpTransport::DEFAULT_HOST,
        'port' => \Gelf\Transport\TcpTransport::DEFAULT_PORT,
        'sslOptions' => null,
        'useSsl' => false,
    ];

    protected array $propertyMapping = [
        'logLevel' => 'string',
        'shouldBubble' => 'bool',
        'host' => 'string',
        'port' => 'int',
        'sslOptions' => '\\Everon\\Logger\\Configurator\\Plugin\\GelfLoggerPluginSslOptions',
        'useSsl' => 'bool',
    ];

    protected array $collectionItems = [
    ];

    protected array $updateMap = [];

    /**
     * @param string $property
     *
     * @return mixed|null
     */
    protected function popoGetValue(string $property)
    {
        if (!isset($this->data[$property])) {
            if ($this->typeIsObject($this->propertyMapping[$property])) {
                $popo = new $this->propertyMapping[$property];
                $this->data[$property] = $popo;
            }
            else {
                return null;
            }
        }

        return $this->data[$property];
    }

    /**
     * @param string $property
     * @param mixed $value
     *
     * @return void
     */
    protected function popoSetValue(string $property, $value): void
    {
        $this->data[$property] = $value;

        $this->updateMap[$property] = true;
    }

    /**
     * @param string $property
     *
     * @return void
     * @throws UnexpectedValueException
     */
    protected function assertPropertyValue(string $property): void
    {
        if (!isset($this->data[$property])) {
            throw new UnexpectedValueException(sprintf(
                'Required value of "%s" has not been set',
                $property
            ));
        }
    }

    /**
     * @param string $propertyName
     * @param mixed $value
     *
     * @return void
     * @throws \InvalidArgumentException
     */
    protected function addCollectionItem(string $propertyName, $value): void
    {
        $type = trim(strtolower($this->propertyMapping[$propertyName]));
        $collection = $this->popoGetValue($propertyName) ?? [];

        if (!is_array($collection) || $type !== 'array') {
            throw new InvalidArgumentException('Cannot add item to non array type: ' . $propertyName);
        }

        $collection[] = $value;

        $this->popoSetValue($propertyName, $collection);
    }

    public function toArray(): array
    {
        $data = [];

        foreach ($this->propertyMapping as $key => $type) {
            if (!array_key_exists($key, $data)) {
                $data[$key] = $this->default[$key] ?? null;
            }
            $value = $this->data[$key];

            if ($this->isCollectionItem($key) && is_array($value)) {
                foreach ($value as $popo) {
                    if (is_object($popo) && method_exists($popo, 'toArray')) {
                        $data[$key][] = $popo->toArray();
                    }
                }

                continue;
            }

            if (is_object($value) && method_exists($value, 'toArray')) {
                $data[$key] = $value->toArray();
                continue;
            }

            $data[$key] = $value;
        }

        return $data;
    }

    public function fromArray(array $data): GelfTcpLoggerPluginConfigurator
    {
        foreach ($this->propertyMapping as $key => $type) {
            $result[$key] = $this->default[$key] ?? null;

            if ($this->typeIsObject($type)) {
                $popo = new $this->propertyMapping[$key];
                if (method_exists($popo, 'fromArray')) {
                    $popoData = $data[$key] ?? $this->default[$key] ?? [];
                    $popo->fromArray($popoData);
                }
                $result[$key] = $popo;

                continue;
            }

            if (array_key_exists($key, $data)) {
                if ($this->isCollectionItem($key)) {
                    foreach ($data[$key] as $popoData) {
                        $popo = new $this->collectionItems[$key]();
                        if (method_exists($popo, 'fromArray')) {
                            $popo->fromArray($popoData);
                        }
                        $result[$key][] = $popo;
                    }
                }
                else {
                    $result[$key] = $data[$key];
                }
            }
        }

        $this->data = $result;

        foreach ($data as $key => $value) {
            if (!array_key_exists($key, $result)) {
                continue;
            }

            $type = $this->propertyMapping[$key] ?? null;
            if ($type !== null) {
                $value = $this->typecastValue($type, $result[$key]);
                $this->popoSetValue($key, $value);
            }
        }

        return $this;
    }

    /**
     * @param string $type
     * @param mixed $value
     *
     * @return mixed
     */
    protected function typecastValue(string $type, $value)
    {
        if ($value === null) {
            return $value;
        }

        switch ($type) {
            case 'int':
                $value = (int) $value;
                break;
            case 'string':
                $value = (string) $value;
                break;
            case 'bool':
                $value = (bool) $value;
                break;
            case 'array':
                $value = (array) $value;
                break;
        }

        return $value;
    }

    protected function isCollectionItem(string $key): bool
    {
        return array_key_exists($key, $this->collectionItems);
    }

    protected function typeIsObject(string $value): bool
    {
        return $value[0] === '\\' && ctype_upper($value[1]);
    }

    /**
     * @return string|null
     */
    public function getLogLevel(): ?string
    {
        return $this->popoGetValue('logLevel');
    }

    /**
     * @param string|null $logLevel
     *
     * @return GelfTcpLoggerPluginConfigurator
     */
    public function setLogLevel(?string $logLevel): GelfTcpLoggerPluginConfigurator
    {
        $this->popoSetValue('logLevel', $logLevel);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return string
     * @throws \UnexpectedValueException
     *
     */
    public function requireLogLevel(): string
    {
        $this->assertPropertyValue('logLevel');

        return (string) $this->popoGetValue('logLevel');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasLogLevel(): bool
    {
        return $this->updateMap['logLevel'] ?? false;
    }

    /**
     * @return boolean|null
     */
    public function shouldBubble(): ?bool
    {
        return $this->popoGetValue('shouldBubble');
    }

    /**
     * @param boolean|null $shouldBubble
     *
     * @return GelfTcpLoggerPluginConfigurator
     */
    public function setShouldBubble(?bool $shouldBubble): GelfTcpLoggerPluginConfigurator
    {
        $this->popoSetValue('shouldBubble', $shouldBubble);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return boolean
     * @throws \UnexpectedValueException
     *
     */
    public function requireShouldBubble(): bool
    {
        $this->assertPropertyValue('shouldBubble');

        return (bool) $this->popoGetValue('shouldBubble');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasShouldBubble(): bool
    {
        return $this->updateMap['shouldBubble'] ?? false;
    }

    /**
     * @return string|null
     */
    public function getHost(): ?string
    {
        return $this->popoGetValue('host');
    }

    /**
     * @param string|null $host
     *
     * @return GelfTcpLoggerPluginConfigurator
     */
    public function setHost(?string $host): GelfTcpLoggerPluginConfigurator
    {
        $this->popoSetValue('host', $host);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return string
     * @throws \UnexpectedValueException
     *
     */
    public function requireHost(): string
    {
        $this->assertPropertyValue('host');

        return (string) $this->popoGetValue('host');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasHost(): bool
    {
        return $this->updateMap['host'] ?? false;
    }

    /**
     * @return integer|null
     */
    public function getPort(): ?int
    {
        return $this->popoGetValue('port');
    }

    /**
     * @param integer|null $port
     *
     * @return GelfTcpLoggerPluginConfigurator
     */
    public function setPort(?int $port): GelfTcpLoggerPluginConfigurator
    {
        $this->popoSetValue('port', $port);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return integer
     * @throws \UnexpectedValueException
     *
     */
    public function requirePort(): int
    {
        $this->assertPropertyValue('port');

        return (int) $this->popoGetValue('port');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasPort(): bool
    {
        return $this->updateMap['port'] ?? false;
    }

    /**
     * @return GelfLoggerPluginSslOptions|null
     */
    public function getSslOptions(): ?GelfLoggerPluginSslOptions
    {
        return $this->popoGetValue('sslOptions');
    }

    /**
     * @param GelfLoggerPluginSslOptions|null $sslOptions
     *
     * @return GelfTcpLoggerPluginConfigurator
     */
    public function setSslOptions(?GelfLoggerPluginSslOptions $sslOptions): GelfTcpLoggerPluginConfigurator
    {
        $this->popoSetValue('sslOptions', $sslOptions);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return GelfLoggerPluginSslOptions
     * @throws \UnexpectedValueException
     *
     */
    public function requireSslOptions(): GelfLoggerPluginSslOptions
    {
        $this->assertPropertyValue('sslOptions');

        return $this->popoGetValue('sslOptions');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasSslOptions(): bool
    {
        return $this->updateMap['sslOptions'] ?? false;
    }

    /**
     * @return boolean|null
     */
    public function useSsl(): ?bool
    {
        return $this->popoGetValue('useSsl');
    }

    /**
     * @param boolean|null $useSsl
     *
     * @return GelfTcpLoggerPluginConfigurator
     */
    public function setUseSsl(?bool $useSsl): GelfTcpLoggerPluginConfigurator
    {
        $this->popoSetValue('useSsl', $useSsl);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return boolean
     * @throws \UnexpectedValueException
     *
     */
    public function requireUseSsl(): bool
    {
        $this->assertPropertyValue('useSsl');

        return (bool) $this->popoGetValue('useSsl');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasUseSsl(): bool
    {
        return $this->updateMap['useSsl'] ?? false;
    }
}
