<?php declare(strict_types = 1);

namespace Everon\Logger\Configurator\Plugin;

use InvalidArgumentException;
use UnexpectedValueException;
use function array_key_exists;
use function ctype_upper;
use function is_array;
use function is_object;
use function method_exists;
use function sprintf;
use function strtolower;
use function trim;

/**
 * Code generated by POPO generator, do not edit.
 * https://packagist.org/packages/popo/generator
 */
class LoggerPluginConfigurator
{
    protected array $data = [
        'name' => 'everon-logger',
        'timezone' => 'UTC',
        'pluginClassCollection' =>
            [
            ],
        'processorClassCollection' =>
            [
            ],
        'gelfConfigurator' => null,
        'redisConfigurator' => null,
        'streamConfigurator' => null,
        'syslogConfigurator' => null,
    ];

    protected array $default = [
        'name' => 'everon-logger',
        'timezone' => 'UTC',
        'pluginClassCollection' =>
            [
            ],
        'processorClassCollection' =>
            [
            ],
        'gelfConfigurator' => null,
        'redisConfigurator' => null,
        'streamConfigurator' => null,
        'syslogConfigurator' => null,
    ];

    protected array $propertyMapping = [
        'name' => 'string',
        'timezone' => 'string',
        'pluginClassCollection' => 'array',
        'processorClassCollection' => 'array',
        'gelfConfigurator' => '\\Everon\\Logger\\Configurator\\Plugin\\GelfLoggerPluginConfigurator',
        'redisConfigurator' => '\\Everon\\Logger\\Configurator\\Plugin\\RedisLoggerPluginConfigurator',
        'streamConfigurator' => '\\Everon\\Logger\\Configurator\\Plugin\\StreamLoggerPluginConfigurator',
        'syslogConfigurator' => '\\Everon\\Logger\\Configurator\\Plugin\\SyslogLoggerPluginConfigurator',
    ];

    protected array $collectionItems = [
    ];

    protected array $updateMap = [];

    public function toArray(): array
    {
        $data = [];

        foreach ($this->propertyMapping as $key => $type) {
            if (!array_key_exists($key, $data)) {
                $data[$key] = $this->default[$key] ?? null;
            }
            $value = $this->data[$key];

            if ($this->isCollectionItem($key) && is_array($value)) {
                foreach ($value as $popo) {
                    if (is_object($popo) && method_exists($popo, 'toArray')) {
                        $data[$key][] = $popo->toArray();
                    }
                }

                continue;
            }

            if (is_object($value) && method_exists($value, 'toArray')) {
                $data[$key] = $value->toArray();
                continue;
            }

            $data[$key] = $value;
        }

        return $data;
    }

    protected function isCollectionItem(string $key): bool
    {
        return array_key_exists($key, $this->collectionItems);
    }

    public function fromArray(array $data): LoggerPluginConfigurator
    {
        foreach ($this->propertyMapping as $key => $type) {
            $result[$key] = $this->default[$key] ?? null;

            if ($this->typeIsObject($type)) {
                $popo = new $this->propertyMapping[$key];
                if (method_exists($popo, 'fromArray')) {
                    $popoData = $data[$key] ?? $this->default[$key] ?? [];
                    $popo->fromArray($popoData);
                }
                $result[$key] = $popo;

                continue;
            }

            if (array_key_exists($key, $data)) {
                if ($this->isCollectionItem($key)) {
                    foreach ($data[$key] as $popoData) {
                        $popo = new $this->collectionItems[$key]();
                        if (method_exists($popo, 'fromArray')) {
                            $popo->fromArray($popoData);
                        }
                        $result[$key][] = $popo;
                    }
                }
                else {
                    $result[$key] = $data[$key];
                }
            }
        }

        $this->data = $result;

        foreach ($data as $key => $value) {
            if (!array_key_exists($key, $result)) {
                continue;
            }

            $type = $this->propertyMapping[$key] ?? null;
            if ($type !== null) {
                $value = $this->typecastValue($type, $result[$key]);
                $this->popoSetValue($key, $value);
            }
        }

        return $this;
    }

    protected function typeIsObject(string $value): bool
    {
        return $value[0] === '\\' && ctype_upper($value[1]);
    }

    /**
     * @param string $type
     * @param mixed $value
     *
     * @return mixed
     */
    protected function typecastValue(string $type, $value)
    {
        if ($value === null) {
            return $value;
        }

        switch ($type) {
            case 'int':
                $value = (int) $value;
                break;
            case 'string':
                $value = (string) $value;
                break;
            case 'bool':
                $value = (bool) $value;
                break;
            case 'array':
                $value = (array) $value;
                break;
        }

        return $value;
    }

    /**
     * @param string $property
     * @param mixed $value
     *
     * @return void
     */
    protected function popoSetValue(string $property, $value): void
    {
        $this->data[$property] = $value;

        $this->updateMap[$property] = true;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->popoGetValue('name');
    }

    /**
     * @param string $property
     *
     * @return mixed|null
     */
    protected function popoGetValue(string $property)
    {
        if (!isset($this->data[$property])) {
            if ($this->typeIsObject($this->propertyMapping[$property])) {
                $popo = new $this->propertyMapping[$property];
                $this->data[$property] = $popo;
            }
            else {
                return null;
            }
        }

        return $this->data[$property];
    }

    /**
     * @param string|null $name
     *
     * @return LoggerPluginConfigurator
     */
    public function setName(?string $name): LoggerPluginConfigurator
    {
        $this->popoSetValue('name', $name);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return string
     * @throws \UnexpectedValueException
     *
     */
    public function requireName(): string
    {
        $this->assertPropertyValue('name');

        return (string) $this->popoGetValue('name');
    }

    /**
     * @param string $property
     *
     * @return void
     * @throws UnexpectedValueException
     */
    protected function assertPropertyValue(string $property): void
    {
        if (!isset($this->data[$property])) {
            throw new UnexpectedValueException(sprintf(
                'Required value of "%s" has not been set',
                $property
            ));
        }
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasName(): bool
    {
        return $this->updateMap['name'] ?? false;
    }

    /**
     * @return string|null
     */
    public function getTimezone(): ?string
    {
        return $this->popoGetValue('timezone');
    }

    /**
     * @param string|null $timezone
     *
     * @return LoggerPluginConfigurator
     */
    public function setTimezone(?string $timezone): LoggerPluginConfigurator
    {
        $this->popoSetValue('timezone', $timezone);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return string
     * @throws \UnexpectedValueException
     *
     */
    public function requireTimezone(): string
    {
        $this->assertPropertyValue('timezone');

        return (string) $this->popoGetValue('timezone');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasTimezone(): bool
    {
        return $this->updateMap['timezone'] ?? false;
    }

    /**
     * @return array|null
     */
    public function getPluginClassCollection(): ?array
    {
        return $this->popoGetValue('pluginClassCollection');
    }

    /**
     * @param array|null $pluginClassCollection
     *
     * @return LoggerPluginConfigurator
     */
    public function setPluginClassCollection(?array $pluginClassCollection): LoggerPluginConfigurator
    {
        $this->popoSetValue('pluginClassCollection', $pluginClassCollection);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return array
     * @throws \UnexpectedValueException
     *
     */
    public function requirePluginClassCollection(): array
    {
        $this->assertPropertyValue('pluginClassCollection');

        return (array) $this->popoGetValue('pluginClassCollection');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasPluginClassCollection(): bool
    {
        return $this->updateMap['pluginClassCollection'] ?? false;
    }

    /**
     * @return array|null
     */
    public function getProcessorClassCollection(): ?array
    {
        return $this->popoGetValue('processorClassCollection');
    }

    /**
     * @param array|null $processorClassCollection
     *
     * @return LoggerPluginConfigurator
     */
    public function setProcessorClassCollection(?array $processorClassCollection): LoggerPluginConfigurator
    {
        $this->popoSetValue('processorClassCollection', $processorClassCollection);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return array
     * @throws \UnexpectedValueException
     *
     */
    public function requireProcessorClassCollection(): array
    {
        $this->assertPropertyValue('processorClassCollection');

        return (array) $this->popoGetValue('processorClassCollection');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasProcessorClassCollection(): bool
    {
        return $this->updateMap['processorClassCollection'] ?? false;
    }

    /**
     * @return GelfLoggerPluginConfigurator|null
     */
    public function getGelfConfigurator(): ?GelfLoggerPluginConfigurator
    {
        return $this->popoGetValue('gelfConfigurator');
    }

    /**
     * @param GelfLoggerPluginConfigurator|null $gelfConfigurator
     *
     * @return LoggerPluginConfigurator
     */
    public function setGelfConfigurator(?GelfLoggerPluginConfigurator $gelfConfigurator): LoggerPluginConfigurator
    {
        $this->popoSetValue('gelfConfigurator', $gelfConfigurator);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return GelfLoggerPluginConfigurator
     * @throws \UnexpectedValueException
     *
     */
    public function requireGelfConfigurator(): GelfLoggerPluginConfigurator
    {
        $this->assertPropertyValue('gelfConfigurator');

        return $this->popoGetValue('gelfConfigurator');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasGelfConfigurator(): bool
    {
        return $this->updateMap['gelfConfigurator'] ?? false;
    }

    /**
     * @return RedisLoggerPluginConfigurator|null
     */
    public function getRedisConfigurator(): ?RedisLoggerPluginConfigurator
    {
        return $this->popoGetValue('redisConfigurator');
    }

    /**
     * @param RedisLoggerPluginConfigurator|null $redisConfigurator
     *
     * @return LoggerPluginConfigurator
     */
    public function setRedisConfigurator(?RedisLoggerPluginConfigurator $redisConfigurator): LoggerPluginConfigurator
    {
        $this->popoSetValue('redisConfigurator', $redisConfigurator);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return RedisLoggerPluginConfigurator
     * @throws \UnexpectedValueException
     *
     */
    public function requireRedisConfigurator(): RedisLoggerPluginConfigurator
    {
        $this->assertPropertyValue('redisConfigurator');

        return $this->popoGetValue('redisConfigurator');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasRedisConfigurator(): bool
    {
        return $this->updateMap['redisConfigurator'] ?? false;
    }

    /**
     * @return StreamLoggerPluginConfigurator|null
     */
    public function getStreamConfigurator(): ?StreamLoggerPluginConfigurator
    {
        return $this->popoGetValue('streamConfigurator');
    }

    /**
     * @param StreamLoggerPluginConfigurator|null $streamConfigurator
     *
     * @return LoggerPluginConfigurator
     */
    public function setStreamConfigurator(?StreamLoggerPluginConfigurator $streamConfigurator): LoggerPluginConfigurator
    {
        $this->popoSetValue('streamConfigurator', $streamConfigurator);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return StreamLoggerPluginConfigurator
     * @throws \UnexpectedValueException
     *
     */
    public function requireStreamConfigurator(): StreamLoggerPluginConfigurator
    {
        $this->assertPropertyValue('streamConfigurator');

        return $this->popoGetValue('streamConfigurator');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasStreamConfigurator(): bool
    {
        return $this->updateMap['streamConfigurator'] ?? false;
    }

    /**
     * @return SyslogLoggerPluginConfigurator|null
     */
    public function getSyslogConfigurator(): ?SyslogLoggerPluginConfigurator
    {
        return $this->popoGetValue('syslogConfigurator');
    }

    /**
     * @param SyslogLoggerPluginConfigurator|null $syslogConfigurator
     *
     * @return LoggerPluginConfigurator
     */
    public function setSyslogConfigurator(?SyslogLoggerPluginConfigurator $syslogConfigurator): LoggerPluginConfigurator
    {
        $this->popoSetValue('syslogConfigurator', $syslogConfigurator);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return SyslogLoggerPluginConfigurator
     * @throws \UnexpectedValueException
     *
     */
    public function requireSyslogConfigurator(): SyslogLoggerPluginConfigurator
    {
        $this->assertPropertyValue('syslogConfigurator');

        return $this->popoGetValue('syslogConfigurator');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasSyslogConfigurator(): bool
    {
        return $this->updateMap['syslogConfigurator'] ?? false;
    }

    /**
     * @param $item
     *
     * @return LoggerPluginConfigurator
     */
    public function addPluginClass($item): LoggerPluginConfigurator
    {
        $this->addCollectionItem('pluginClassCollection', $item);

        return $this;
    }

    /**
     * @param string $propertyName
     * @param mixed $value
     *
     * @return void
     * @throws \InvalidArgumentException
     */
    protected function addCollectionItem(string $propertyName, $value): void
    {
        $type = trim(strtolower($this->propertyMapping[$propertyName]));
        $collection = $this->popoGetValue($propertyName) ?? [];

        if (!is_array($collection) || $type !== 'array') {
            throw new InvalidArgumentException('Cannot add item to non array type: ' . $propertyName);
        }

        $collection[] = $value;

        $this->popoSetValue($propertyName, $collection);
    }

    /**
     * @param $item
     *
     * @return LoggerPluginConfigurator
     */
    public function addProcessorClass($item): LoggerPluginConfigurator
    {
        $this->addCollectionItem('processorClassCollection', $item);

        return $this;
    }
}
